### ISSUE TITLE
libavformat branch: fatal error

### ISSUE THREAD

**Issue by nightshining** [bangnoise/ofxHapPlayer#22]
Hello,
I'm trying to run the example for **_ofxHapPlayer > libavformat branch_** on **_openframeworks release 9.8_** on a mac 10.11. After I have installed the proper codecs based on the readme via _**brew install**_ I try to build the example project and I get the following error.

_**dyld: Library not loaded: libavcodec.57.dylib
  Referenced from: /Users/FakeMike/Desktop/of_v0.9.8_osx_release/addons/ofxHapPlayer/example/bin/example.app/Contents/MacOS/example
  Reason: image not found
(lldb)**_

**Comment by bangnoise** [comment]
You don't need to install the libraries on macOS, the right versions are bundled with the addon. I'll make the README clearer about that.

Are you building with Xcode?

**Comment by bangnoise** [comment]
Oops just reproduced this, investigating

**Comment by bangnoise** [comment]
OK, pull now, it should work..?

**Comment by nightshining** [comment]
Ok thanks so much for the quick response. Just did a pull, then build and just got this error:

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/FakeMike/Desktop/of_v0.9.8_osx_release/addons/ofxHapPlayer/example/bin/example.app/Contents/MacOS/../../../../../../../addons/ofxHapPlayer/libs/ffmpeg/lib/osx/libavutil.55.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/Username/Desktop/of_v0.9.8_osx_release/addons/ofxHapPlayer/example/bin/example.app/Contents/MacOS/../../../../../../../addons/ofxHapPlayer/libs/ffmpeg/lib/osx/libavutil.55.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

(lldb)_

**Comment by bangnoise** [comment]
OK, I'll see if I can persuade ffmpeg to build with support for 10.11, and update the libraries. In the meantime, it should work on 10.12 if you have a system you can use.

**Comment by bangnoise** [comment]
Okay, should work on macOS 10.10+ now, let me know

**Comment by bangnoise** [comment]
Closing, assumed fixed

**Comment by ludiccc** [comment]
I've got the same problem as described on the begining of this thread. 
The issue is that if I place the code on a different folder than the OF main folder (i.e. /users/me/Development/myAppsFolder/newApp/ instead of /users/me/Development/of_v0.9.8_osx_release/apps/newApp/) the linker is unable to find the dylib. 

I managed to fix it changing the value in "Other Linker Flags" to:
@loader_path/../../../../../../of_v0.9.8_osx_release/addons/ofxHapPlayer/libs
